### ISSUE TITLE
D-Bus service name "com.redhat.oddjob_gpupdate" needs to be rename

### ISSUE THREAD

**Issue by filipavel** [altlinux/oddjob-gpupdate#2]
Hi, 

I am packaging oddjob-gpupdate for Fedora - see https://bugzilla.redhat.com/show_bug.cgi?id=2091668
It was suggested to rename D-Bus service name  "com.redhat.oddjob_gpupdate"  to e.g. "org.altlinux.oddjob_gpupdate".

Let me know if I can create PR for that and if "org.altlinux.oddjob_gpupdate" is a good name.

Best regards,
Pavel

**Comment by mastersin** [comment]
Hello, Pavel,

I think this name looks good. Another case could be start with "ru.basealt." prefix. Both of them are suitable. But I prefer ''ru.basealt.oddjob_gpupdate" due it is a part of Group Policy project and other staff integrated into BaseALT distributions.

**Comment by filipavel** [comment]
Merged as https://github.com/altlinux/oddjob-gpupdate/pull/3
